<?php

use Illuminate\Database\Seeder;

class AnimalBreedsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker\Factory::create();

        $breeds= array(
            ['species_id'=>1,'name'=>'AIREDALE TERRIER'],
            ['species_id'=>1,'name'=>'AKITA AMERYKAŃSKA'],
            ['species_id'=>1,'name'=>'AKITA'],
            ['species_id'=>1,'name'=>'ALASKAN MALAMUTE'],
            ['species_id'=>1,'name'=>'ALPEJSKI GOŃCZY KRÓTKONOŻNY'],
            ['species_id'=>1,'name'=>'AMERICAN STAFFORDSHIRE TERRIER'],
            ['species_id'=>1,'name'=>'AMERYKAŃSKI PITBULTERIER (PITBUL)'],
            ['species_id'=>1,'name'=>'ANATOLIAN'],
            ['species_id'=>1,'name'=>'APPENZELLER'],
            ['species_id'=>1,'name'=>'AUSTRALIAN CATTLE DOG'],
            ['species_id'=>1,'name'=>'AUSTRALIAN SILKY TERRIER'],
            ['species_id'=>1,'name'=>'AUSTRALIAN STUMPY TAIL CATTLE DOG'],
            ['species_id'=>1,'name'=>'BARBET'],
            ['species_id'=>1,'name'=>'BASENJI'],
            ['species_id'=>1,'name'=>'BASSET ARTEZYJSKO-NORMANDZKI'],
            ['species_id'=>1,'name'=>'BASSET HOUND'],
            ['species_id'=>1,'name'=>'BEAGLE'],
            ['species_id'=>1,'name'=>'BEARDED COLLIE'],
            ['species_id'=>1,'name'=>'BEDLINGTON TERRIER'],
            ['species_id'=>1,'name'=>'BERGAMASCO'],
            ['species_id'=>1,'name'=>'BERNARDYN'],
            ['species_id'=>1,'name'=>'BERNEŃSKI PIES PASTERSKI'],
            ['species_id'=>1,'name'=>'BIAŁY OWCZAREK SZWAJCARSKI'],
            ['species_id'=>1,'name'=>'BICHON FRISE'],
            ['species_id'=>1,'name'=>'BLOODHOUND (PIES ŚW. HUBERTA)'],
            ['species_id'=>1,'name'=>'BOERBOEL'],
            ['species_id'=>1,'name'=>'BOKSER'],
            ['species_id'=>1,'name'=>'BOLOŃCZYK'],
            ['species_id'=>1,'name'=>'BORDER COLLIE'],
            ['species_id'=>1,'name'=>'BORDER TERRIER'],
            ['species_id'=>1,'name'=>'BOSTON TERRIER'],
            ['species_id'=>1,'name'=>'BRAQUE DAUVERGNE'],
            ['species_id'=>1,'name'=>'BROHOLMER'],
            ['species_id'=>1,'name'=>'BULDOG ANGIELSKI'],
            ['species_id'=>1,'name'=>'BULDOG FRANCUSKI'],
            ['species_id'=>1,'name'=>'BULLMASTIFF'],
            ['species_id'=>1,'name'=>'BULTERIER MINIATUROWY'],
            ['species_id'=>1,'name'=>'BULTERIER'],
            ['species_id'=>1,'name'=>'CAIRN TERRIER'],
            ['species_id'=>1,'name'=>'CANAAN DOG'],
            ['species_id'=>1,'name'=>'CANE CORSO ITALIANO'],
            ['species_id'=>1,'name'=>'CATAHOULA LEOPARD DOG'],
            ['species_id'=>1,'name'=>'CAVALIER KING CHARLES SPANIEL'],
            ['species_id'=>1,'name'=>'CHARCIK WŁOSKI'],
            ['species_id'=>1,'name'=>'CHART AFGAŃSKI'],
            ['species_id'=>1,'name'=>'CHART AFRYKAŃSKI  AZAWAKH'],
            ['species_id'=>1,'name'=>'CHART PERSKI  SALUKI'],
            ['species_id'=>1,'name'=>'CHART POLSKI'],
            ['species_id'=>1,'name'=>'CHART SZKOCKI'],
            ['species_id'=>1,'name'=>'CHART WĘGIERSKI'],
            ['species_id'=>1,'name'=>'CHESAPEAKE BAY RETRIEVER'],
            ['species_id'=>1,'name'=>'CHIHUAHUA'],
            ['species_id'=>1,'name'=>'CHIN JAPOŃSKI'],
            ['species_id'=>1,'name'=>'CHIŃSKI GRZYWACZ'],
            ['species_id'=>1,'name'=>'CHOW-CHOW'],
            ['species_id'=>1,'name'=>'CIRNECO DELLETNA'],
            ['species_id'=>1,'name'=>'CLUMBER SPANIEL'],
            ['species_id'=>1,'name'=>'COCKER SPANIEL AMERYKAŃSKI'],
            ['species_id'=>1,'name'=>'COCKER SPANIEL ANGIELSKI'],
            ['species_id'=>1,'name'=>'COTON DE TULEAR'],
            ['species_id'=>1,'name'=>'CURLY COATED RETRIEVER'],
            ['species_id'=>1,'name'=>'CZARNY TERIER'],
            ['species_id'=>1,'name'=>'DALMATYŃCZYK'],
            ['species_id'=>1,'name'=>'DOBERMAN'],
            ['species_id'=>1,'name'=>'DOG ARGENTYŃSKI'],
            ['species_id'=>1,'name'=>'DOG KANARYJSKI'],
            ['species_id'=>1,'name'=>'DOG NIEMIECKI'],
            ['species_id'=>1,'name'=>'DOG Z MAJORKI'],
            ['species_id'=>1,'name'=>'DOGUE DE BORDEAUX'],
            ['species_id'=>1,'name'=>'DUŃSKO-SZWEDZKI PIES WIEJSKI'],
            ['species_id'=>1,'name'=>'DUŻY SZWAJCARSKI PIES PASTERSKI'],
            ['species_id'=>1,'name'=>'ELKHUND SZARY'],
            ['species_id'=>1,'name'=>'ENTLEBUCHER'],
            ['species_id'=>1,'name'=>'FIELD SPANIEL'],
            ['species_id'=>1,'name'=>'FILA BRASILEIRO'],
            ['species_id'=>1,'name'=>'FLAT COATED RETRIEVER'],
            ['species_id'=>1,'name'=>'FOKSTERIER KRÓTKOWŁOSY'],
            ['species_id'=>1,'name'=>'GOLDEN RETRIEVER'],
            ['species_id'=>1,'name'=>'GOŃCZY BERNEŃSKI'],
            ['species_id'=>1,'name'=>'GOŃCZY FIŃSKI'],
            ['species_id'=>1,'name'=>'GOŃCZY POLSKI'],
            ['species_id'=>1,'name'=>'GOŃCZY SŁOWACKI'],
            ['species_id'=>1,'name'=>'GOŃCZY WĘGIERSKI'],
            ['species_id'=>1,'name'=>'GREYHOUND'],
            ['species_id'=>1,'name'=>'GRYFON KORTHALSA'],
            ['species_id'=>1,'name'=>'GRYFONIK BELGIJSKI'],
            ['species_id'=>1,'name'=>'GRYFONIK BRUKSELSKI'],
            ['species_id'=>1,'name'=>'HAWAŃCZYK'],
            ['species_id'=>1,'name'=>'HISZPAŃSKI PIES DOWODNY'],
            ['species_id'=>1,'name'=>'HOVAWART'],
            ['species_id'=>1,'name'=>'IRISH GLEN OF IMAAL TERRIER'],
            ['species_id'=>1,'name'=>'IRISH SOFT COATED WHEATEN TERRIER'],
            ['species_id'=>1,'name'=>'IRLANDZKI SPANIEL DOWODNY'],
            ['species_id'=>1,'name'=>'ISLANDZKI SZPIC PASTERSKI'],
            ['species_id'=>1,'name'=>'JACK RUSSELL TERRIER'],
            ['species_id'=>1,'name'=>'JAMNIK DŁUGOWŁOSY'],
            ['species_id'=>1,'name'=>'JAMNIK KRÓTKOWŁOSY'],
            ['species_id'=>1,'name'=>'JAMNIK SZORSTKOWŁOSY'],
            ['species_id'=>1,'name'=>'JÄMTHUND'],
            ['species_id'=>1,'name'=>'KAI'],
            ['species_id'=>1,'name'=>'KANGAL'],
            ['species_id'=>1,'name'=>'KARELSKI PIES NA NIEDŹWIEDZIE'],
            ['species_id'=>1,'name'=>'KERRY BLUE TERRIER'],
            ['species_id'=>1,'name'=>'KING CHARLES SPANIEL'],
            ['species_id'=>1,'name'=>'KOMONDOR'],
            ['species_id'=>1,'name'=>'KOOLIE'],
            ['species_id'=>1,'name'=>'LABRADOR RETRIEVER'],
            ['species_id'=>1,'name'=>'LAGOTTO ROMAGNOLO'],
            ['species_id'=>1,'name'=>'LANCASHIRE HEELER'],
            ['species_id'=>1,'name'=>'LANDSEER'],
            ['species_id'=>1,'name'=>'LEONBERGER'],
            ['species_id'=>1,'name'=>'LHASA APSO'],
            ['species_id'=>1,'name'=>'LWI PIESEK'],
            ['species_id'=>1,'name'=>'MALTAŃCZYK'],
            ['species_id'=>1,'name'=>'MANCHESTER TERRIER'],
            ['species_id'=>1,'name'=>'MASTIF ANGIELSKI'],
            ['species_id'=>1,'name'=>'MASTIF HISZPAŃSKI'],
            ['species_id'=>1,'name'=>'MASTIF NEAPOLITAŃSKI'],
            ['species_id'=>1,'name'=>'MASTIF PIRENEJSKI'],
            ['species_id'=>1,'name'=>'MASTIF TYBETAŃSKI'],
            ['species_id'=>1,'name'=>'MAŁY GOŃCZY GASKOŃSKI'],
            ['species_id'=>1,'name'=>'MAŁY MÜNSTERLÄNDER'],
            ['species_id'=>1,'name'=>'MOPS'],
            ['species_id'=>1,'name'=>'MUDI'],
            ['species_id'=>1,'name'=>'NAGI PIES MEKSYKAŃSKI'],
            ['species_id'=>1,'name'=>'NAGI PIES PERUWIAŃSKI'],
            ['species_id'=>1,'name'=>'NIEMIECKI TERIER MYŚLIWSKI'],
            ['species_id'=>1,'name'=>'NORFOLK TERRIER'],
            ['species_id'=>1,'name'=>'NORWICH TERRIER'],
            ['species_id'=>1,'name'=>'NOVA SCOTIA DUCK TOLLING RETRIEVER'],
            ['species_id'=>1,'name'=>'NOWOFUNDLAND'],
            ['species_id'=>1,'name'=>'OGAR POLSKI'],
            ['species_id'=>1,'name'=>'OWCZAREK AUSTRALIJSKI  KELPIE'],
            ['species_id'=>1,'name'=>'OWCZAREK AUSTRALIJSKI (TYP AMERYKAŃSKI)'],
            ['species_id'=>1,'name'=>'OWCZAREK BELGIJSKI GROENENDAEL'],
            ['species_id'=>1,'name'=>'OWCZAREK BELGIJSKI LAEKENOIS'],
            ['species_id'=>1,'name'=>'OWCZAREK BELGIJSKI MALINOIS'],
            ['species_id'=>1,'name'=>'OWCZAREK BELGIJSKI TERVUEREN'],
            ['species_id'=>1,'name'=>'OWCZAREK CHORWACKI'],
            ['species_id'=>1,'name'=>'OWCZAREK FRANCUSKI BEAUCERON'],
            ['species_id'=>1,'name'=>'OWCZAREK GRECKI'],
            ['species_id'=>1,'name'=>'OWCZAREK HOLENDERSKI DŁUGOWŁOSY'],
            ['species_id'=>1,'name'=>'OWCZAREK HOLENDERSKI KRÓTKOWŁOSY'],
            ['species_id'=>1,'name'=>'OWCZAREK KATALOŃSKI'],
            ['species_id'=>1,'name'=>'OWCZAREK KAUKASKI'],
            ['species_id'=>1,'name'=>'OWCZAREK NIEMIECKI'],
            ['species_id'=>1,'name'=>'OWCZAREK PIKARDYJSKI'],
            ['species_id'=>1,'name'=>'OWCZAREK PIRENEJSKI O GŁADKIEJ KUFIE'],
            ['species_id'=>1,'name'=>'OWCZAREK PODHALAŃSKI'],
            ['species_id'=>1,'name'=>'OWCZAREK PORTUGALSKI'],
            ['species_id'=>1,'name'=>'OWCZAREK STAROANGIELSKI BOBTAIL'],
            ['species_id'=>1,'name'=>'OWCZAREK SZETLANDZKI (SHELTIE)'],
            ['species_id'=>1,'name'=>'OWCZAREK SZKOCKI DŁUGOWŁOSY'],
            ['species_id'=>1,'name'=>'OWCZAREK ŚRODKOWOAZJATYCKI'],
            ['species_id'=>1,'name'=>'PARSON RUSSELL TERRIER'],
            ['species_id'=>1,'name'=>'PEKIŃCZYK'],
            ['species_id'=>1,'name'=>'PIES CHODSKI'],
            ['species_id'=>1,'name'=>'PIES FARAONA'],
            ['species_id'=>1,'name'=>'PIES GRENLANDZKI'],
            ['species_id'=>1,'name'=>'PINCZER MINIATUROWY'],
            ['species_id'=>1,'name'=>'PINCZER ŚREDNI'],
            ['species_id'=>1,'name'=>'PIRENEJSKI PIES GÓRSKI'],
            ['species_id'=>1,'name'=>'PODENGO PORTUGALSKI MINIATUROWY'],
            ['species_id'=>1,'name'=>'POINTER'],
            ['species_id'=>1,'name'=>'POITEVIN'],
            ['species_id'=>1,'name'=>'POLSKI OWCZAREK NIZINNY (PON)'],
            ['species_id'=>1,'name'=>'PORTUGALSKI PIES DOWODNY'],
            ['species_id'=>1,'name'=>'POSOKOWIEC BAWARSKI'],
            ['species_id'=>1,'name'=>'POSOKOWIEC HANOWERSKI'],
            ['species_id'=>1,'name'=>'PUDEL DUŻY'],
            ['species_id'=>1,'name'=>'PUDEL MINIATUROWY'],
            ['species_id'=>1,'name'=>'PUDEL TOY'],
            ['species_id'=>1,'name'=>'PUDEL ŚREDNI'],
            ['species_id'=>1,'name'=>'PULI'],
            ['species_id'=>1,'name'=>'PUMI'],
            ['species_id'=>1,'name'=>'PŁOCHACZ NIEMIECKI'],
            ['species_id'=>1,'name'=>'RHODESIAN RIDGEBACK'],
            ['species_id'=>1,'name'=>'ROSYJSKI TOY'],
            ['species_id'=>1,'name'=>'ROTTWEILER'],
            ['species_id'=>1,'name'=>'SAARLOOSWOLFHOND'],
            ['species_id'=>1,'name'=>'SAMOJED'],
            ['species_id'=>1,'name'=>'SCHAPENDOES'],
            ['species_id'=>1,'name'=>'SCHIPPERKE'],
            ['species_id'=>1,'name'=>'SETER ANGIELSKI'],
            ['species_id'=>1,'name'=>'SETER IRLANDZKI CZERWONO-BIAŁY'],
            ['species_id'=>1,'name'=>'SETER IRLANDZKI'],
            ['species_id'=>1,'name'=>'SETER SZKOCKI (GORDON)'],
            ['species_id'=>1,'name'=>'SHAR PEI'],
            ['species_id'=>1,'name'=>'SHIBA'],
            ['species_id'=>1,'name'=>'SHIH TZU'],
            ['species_id'=>1,'name'=>'SHIKOKU'],
            ['species_id'=>1,'name'=>'SIBERIAN HUSKY (HUSKY SYBERYJSKI)'],
            ['species_id'=>1,'name'=>'SKYE TERRIER'],
            ['species_id'=>1,'name'=>'SPANIEL BRETOŃSKI'],
            ['species_id'=>1,'name'=>'SPANIEL KONTYNENTALNY MINIATUROWY  PAPILLON'],
            ['species_id'=>1,'name'=>'SPANIEL TYBETAŃSKI'],
            ['species_id'=>1,'name'=>'SPRINGER SPANIEL ANGIELSKI'],
            ['species_id'=>1,'name'=>'SPRINGER SPANIEL WALIJSKI'],
            ['species_id'=>1,'name'=>'STAFFORDSHIRE BULL TERRIER'],
            ['species_id'=>1,'name'=>'SUOMENLAPINKOIRA'],
            ['species_id'=>1,'name'=>'SZNAUCER MINIATUROWY'],
            ['species_id'=>1,'name'=>'SZNAUCER OLBRZYM'],
            ['species_id'=>1,'name'=>'SZNAUCER ŚREDNI'],
            ['species_id'=>1,'name'=>'SZPIC DUŻY'],
            ['species_id'=>1,'name'=>'SZPIC FIŃSKI'],
            ['species_id'=>1,'name'=>'SZPIC JAPOŃSKI'],
            ['species_id'=>1,'name'=>'SZPIC MAŁY'],
            ['species_id'=>1,'name'=>'SZPIC MINIATUROWY (POMERANIAN)'],
            ['species_id'=>1,'name'=>'SZPIC WILCZY'],
            ['species_id'=>1,'name'=>'SZPIC ŚREDNI'],
            ['species_id'=>1,'name'=>'TERIER IRLANDZKI'],
            ['species_id'=>1,'name'=>'TERIER SZKOCKI'],
            ['species_id'=>1,'name'=>'TERIER TYBETAŃSKI'],
            ['species_id'=>1,'name'=>'TERIER WALIJSKI'],
            ['species_id'=>1,'name'=>'TOSA'],
            ['species_id'=>1,'name'=>'VÄSTGÖTASPETS'],
            ['species_id'=>1,'name'=>'WELSH CORGI CARDIGAN'],
            ['species_id'=>1,'name'=>'WELSH CORGI PEMBROKE'],
            ['species_id'=>1,'name'=>'WEST HIGHLAND WHITE TERRIER'],
            ['species_id'=>1,'name'=>'WHIPPET'],
            ['species_id'=>1,'name'=>'WILCZAK CZECHOSŁOWACKI'],
            ['species_id'=>1,'name'=>'WILCZARZ IRLANDZKI'],
            ['species_id'=>1,'name'=>'WYŻEŁ FRYZYJSKI (STABYHOUN)'],
            ['species_id'=>1,'name'=>'WYŻEŁ NIEMIECKI KRÓTKOWŁOSY'],
            ['species_id'=>1,'name'=>'WYŻEŁ WEIMARSKI'],
            ['species_id'=>1,'name'=>'WYŻEŁ WĘGIERSKI KRÓTKOWŁOSY'],
            ['species_id'=>1,'name'=>'WYŻEŁ WĘGIERSKI SZORSTKOWŁOSY'],
            ['species_id'=>1,'name'=>'WYŻEŁ WŁOSKI KRÓTKOWŁOSY'],
            ['species_id'=>1,'name'=>'WYŻEŁ WŁOSKI SZORSTKOWŁOSY'],
            ['species_id'=>1,'name'=>'YORKSHIRE TERRIER (PIES YORK MINIATURKA)'],
            ['species_id'=>1,'name'=>'ŁAJKA ZACHODNIOSYBERYJSKA'],
            ['species_id'=>2,'name'=>'AFRODYTY (APHRODITE CAT)'],
            ['species_id'=>2,'name'=>'AMERICAN CURL'],
            ['species_id'=>2,'name'=>'AMERYKAŃSKI KRÓTKOWŁOSY'],
            ['species_id'=>2,'name'=>'AMERYKAŃSKI RYŚ (AMERICAN LYNX)'],
            ['species_id'=>2,'name'=>'ASHERA'],
            ['species_id'=>2,'name'=>'AUSTRALIAN MIST'],
            ['species_id'=>2,'name'=>'BALIJSKI (BALINESE)'],
            ['species_id'=>2,'name'=>'BIRMAŃSKI  ŚWIĘTY  BIRMAŃSKI'],
            ['species_id'=>2,'name'=>'BOMBAJSKI'],
            ['species_id'=>2,'name'=>'BRYTYJSKI DŁUGOWŁOSY (BRITISH LONGHAIR)'],
            ['species_id'=>2,'name'=>'BURMAŃSKI  BURMSKI (BURMESE)'],
            ['species_id'=>2,'name'=>'CEJLOŃSKI (CEYLON'],
            ['species_id'=>2,'name'=>'CEJLOŃSKI (CEYLON)'],
            ['species_id'=>2,'name'=>'CHAUSIE'],
            ['species_id'=>2,'name'=>'CORNISH REX (REX KORNWALIJSKI)'],
            ['species_id'=>2,'name'=>'CYMRIC (DŁUGOWŁOSY MANX)'],
            ['species_id'=>2,'name'=>'DRAGON LI'],
            ['species_id'=>2,'name'=>'EGEJSKI (AEGEAN)'],
            ['species_id'=>2,'name'=>'EGIPSKI MAU (EGYPTIAN MAU)'],
            ['species_id'=>2,'name'=>'EGZOTYCZNY (EXOTIC)'],
            ['species_id'=>2,'name'=>'ELFI'],
            ['species_id'=>2,'name'=>'EUROPEJSKI KRÓTKOWŁOSY'],
            ['species_id'=>2,'name'=>'HAVANA BROWN'],
            ['species_id'=>2,'name'=>'JAPOŃSKI BOBTAIL (MANEKI NEKO)'],
            ['species_id'=>2,'name'=>'JAWAJSKI (JAVANESE)  ORIENTALNY DŁUGOWŁOSY'],
            ['species_id'=>2,'name'=>'JAWAJSKI'],
            ['species_id'=>2,'name'=>'KARTUSKI (CHARTREAUX)'],
            ['species_id'=>2,'name'=>'KHAO MANEE'],
            ['species_id'=>2,'name'=>'KORAT'],
            ['species_id'=>2,'name'=>'KURYLSKI BOBTAIL (KURILIAN BOBTAIL)'],
            ['species_id'=>2,'name'=>'LAPERM KRÓTKOWŁOSY I LAPERM DŁUGOWŁOSY'],
            ['species_id'=>2,'name'=>'LYKOI ( WILKOŁACZY)'],
            ['species_id'=>2,'name'=>'MAINE COON (Majkun)'],
            ['species_id'=>2,'name'=>'MANX'],
            ['species_id'=>2,'name'=>'MUNCHKIN'],
            ['species_id'=>2,'name'=>'NEBELUNG  ROSYJSKI NIEBIESKI DŁUGOWŁOSY'],
            ['species_id'=>2,'name'=>'NEVA MASQUERADE'],
            ['species_id'=>2,'name'=>'NIEMIECKI REX (GERMAN REX)'],
            ['species_id'=>2,'name'=>'NORWESKI LEŚNY'],
            ['species_id'=>2,'name'=>'OCICAT'],
            ['species_id'=>2,'name'=>'OJOS AZULES'],
            ['species_id'=>2,'name'=>'ORIENTALNY KRÓTKOWŁOSY'],
            ['species_id'=>2,'name'=>'PERSKI BIAŁY'],
            ['species_id'=>2,'name'=>'PERSKI COLORPOINT ( HIMALAJSKI)'],
            ['species_id'=>2,'name'=>'PERSKI CZARN'],
            ['species_id'=>2,'name'=>'PERSKI DWUKOLOROWY'],
            ['species_id'=>2,'name'=>'PERSKI DYMNY'],
            ['species_id'=>2,'name'=>'PERSKI KREMOWY'],
            ['species_id'=>2,'name'=>'PERSKI RUDY'],
            ['species_id'=>2,'name'=>'PERSKI SZYLKRETOWY'],
            ['species_id'=>2,'name'=>'PERSKI ZŁOCISTY CIENIOWANY'],
            ['species_id'=>2,'name'=>'PIXIE-BOB'],
            ['species_id'=>2,'name'=>'RAGAMUFFIN'],
            ['species_id'=>2,'name'=>'RAGDOLL'],
            ['species_id'=>2,'name'=>'SAVANNAH'],
            ['species_id'=>2,'name'=>'SELKIRK REX'],
            ['species_id'=>2,'name'=>'SERENGETI'],
            ['species_id'=>2,'name'=>'SESZELSKI KRÓTKOWŁOSY (SEYCHELLOIS SHORTHAIR)'],
            ['species_id'=>2,'name'=>'SFINKS DOŃSKI (DON SPHYNX)'],
            ['species_id'=>2,'name'=>'SFINKS KANADYJSKI (CANADIAN SPHYNX)'],
            ['species_id'=>2,'name'=>'SFINKS PETERSBURSKI (PETERBALD)'],
            ['species_id'=>2,'name'=>'SINGAPURSKI (SINGAPURA)'],
            ['species_id'=>2,'name'=>'SNOWSHOE'],
            ['species_id'=>2,'name'=>'SOKOKE'],
            ['species_id'=>2,'name'=>'SOMALIJSKI (SOMALI CAT)'],
            ['species_id'=>2,'name'=>'SYBERYJSKI (SIBERIAN CAT)'],
            ['species_id'=>2,'name'=>'SYJAMSKI'],
            ['species_id'=>2,'name'=>'SZKOCKI ZWISŁOUCHY (SCOTTISH FOLD)'],
            ['species_id'=>2,'name'=>'TAJSKI (THAY, SYJAM STAREGO TYPU)'],
            ['species_id'=>2,'name'=>'TONKIJSKI (TONKINESE)'],
            ['species_id'=>2,'name'=>'TOYGER'],
            ['species_id'=>2,'name'=>'TURECKA ANGORA'],
            ['species_id'=>2,'name'=>'TURECKI VAN'],
            ['species_id'=>2,'name'=>'UKRAINIAN LEVKOY'],
            ['species_id'=>3,'name'=>'Amercian'],
            ['species_id'=>3,'name'=>'American Crested'],
            ['species_id'=>3,'name'=>'Angora'],
            ['species_id'=>3,'name'=>'Bounce'],
            ['species_id'=>3,'name'=>'Coronet'],
            ['species_id'=>3,'name'=>'Crested'],
            ['species_id'=>3,'name'=>'Curly'],
            ['species_id'=>3,'name'=>'Kurzhaarer Peruaner'],
            ['species_id'=>3,'name'=>'Lunkarya'],
            ['species_id'=>3,'name'=>'Peruwianka'],
            ['species_id'=>3,'name'=>'Rex'],
            ['species_id'=>3,'name'=>'Ridgeback'],
            ['species_id'=>3,'name'=>'Sheltie'],
            ['species_id'=>3,'name'=>'Skinny'],
            ['species_id'=>3,'name'=>'Somali'],
            ['species_id'=>3,'name'=>'Teddy'],
            ['species_id'=>3,'name'=>'Texel'],
            ['species_id'=>3,'name'=>'abisyńska'],
            ['species_id'=>4,'name'=>'Alaska'],
            ['species_id'=>4,'name'=>'Angora Biała'],
            ['species_id'=>4,'name'=>'Castorex'],
            ['species_id'=>4,'name'=>'Hawana'],
            ['species_id'=>4,'name'=>'Hermelin'],
            ['species_id'=>4,'name'=>'Karzełek baran'],
            ['species_id'=>4,'name'=>'Karzełek rex'],
            ['species_id'=>4,'name'=>'Karzełek satynowy'],
            ['species_id'=>4,'name'=>'Karzełek teddy'],
            ['species_id'=>4,'name'=>'Karzełek zajęczak'],
            ['species_id'=>4,'name'=>'Karzełek'],
            ['species_id'=>4,'name'=>'Rex'],
            ['species_id'=>4,'name'=>'Ryś'],
            ['species_id'=>4,'name'=>'angielski baran'],
            ['species_id'=>4,'name'=>'belgijski olbrzym biały'],
            ['species_id'=>4,'name'=>'belgijski olbrzym'],
            ['species_id'=>4,'name'=>'burgundzki'],
            ['species_id'=>4,'name'=>'duński biały'],
            ['species_id'=>4,'name'=>'francuski baran'],
            ['species_id'=>4,'name'=>'francuski srebrzysty'],
            ['species_id'=>4,'name'=>'holenderski'],
            ['species_id'=>4,'name'=>'hotot biały'],
            ['species_id'=>4,'name'=>'japoński'],
            ['species_id'=>4,'name'=>'kalifornijski'],
            ['species_id'=>4,'name'=>'kuna mała'],
            ['species_id'=>4,'name'=>'kuna wielka'],
            ['species_id'=>4,'name'=>'marburski'],
            ['species_id'=>4,'name'=>'mały baran'],
            ['species_id'=>4,'name'=>'morawski olbrzym'],
            ['species_id'=>4,'name'=>'nowozelandzki biały'],
            ['species_id'=>4,'name'=>'nowozelandzki czerwony'],
            ['species_id'=>4,'name'=>'olbrzym srokacz'],
            ['species_id'=>4,'name'=>'podbielany'],
            ['species_id'=>4,'name'=>'podpalany	'],
            ['species_id'=>4,'name'=>'popielniański biały'],
            ['species_id'=>4,'name'=>'rosyjski'],
            ['species_id'=>4,'name'=>'satynowy'],
            ['species_id'=>4,'name'=>'srebrzysty mały'],
            ['species_id'=>4,'name'=>'syjamski wielki'],
            ['species_id'=>4,'name'=>'syjamski'],
            ['species_id'=>4,'name'=>'szynszyl mały'],
            ['species_id'=>4,'name'=>'szynszyl wielki'],
            ['species_id'=>4,'name'=>'termondzki biały'],
            ['species_id'=>4,'name'=>'turyngski'],
            ['species_id'=>4,'name'=>'wiedeński biały'],
            ['species_id'=>4,'name'=>'wiedeński czarny'],
            ['species_id'=>4,'name'=>'wiedeński niebieski'],
            ['species_id'=>4,'name'=>'wiedeński niebiesko-szary'],
            ['species_id'=>4,'name'=>'wiedeński szary'],
            ['species_id'=>4,'name'=>'wielki jasnosrebrzysty'],
            ['species_id'=>4,'name'=>'zajęczak'],
            ['species_id'=>5,'name'=>'CHIŃSKI'],
            ['species_id'=>5,'name'=>'DŻUNGARSKI'],
            ['species_id'=>5,'name'=>'EUROPEJSKI'],
            ['species_id'=>5,'name'=>'ROBOROWSKIEGO'],
            ['species_id'=>5,'name'=>'SYRYJSKI'],
            ['species_id'=>6,'name'=>'Szczur polinezyjski (pacyficzny)'],
            ['species_id'=>6,'name'=>'Szczur wędrowny'],
            ['species_id'=>6,'name'=>'Szczur śniady'],
            ['species_id'=>7,'name'=>'Amazonka'],
            ['species_id'=>7,'name'=>'Ara'],
            ['species_id'=>7,'name'=>'Kakadu'],
            ['species_id'=>7,'name'=>'afrykanka'],
            ['species_id'=>7,'name'=>'aleksandreta'],
            ['species_id'=>7,'name'=>'astryldy'],
            ['species_id'=>7,'name'=>'barwinka'],
            ['species_id'=>7,'name'=>'barwnica'],
            ['species_id'=>7,'name'=>'dama'],
            ['species_id'=>7,'name'=>'gwarki'],
            ['species_id'=>7,'name'=>'katarzynka'],
            ['species_id'=>7,'name'=>'konura'],
            ['species_id'=>7,'name'=>'loresa'],
            ['species_id'=>7,'name'=>'nierozłączka'],
            ['species_id'=>7,'name'=>'nimfa'],
            ['species_id'=>7,'name'=>'papużki faliste'],
            ['species_id'=>7,'name'=>'piona'],
            ['species_id'=>7,'name'=>'żako'],
            ['species_id'=>8,'name'=>'Black Molly'],
            ['species_id'=>8,'name'=>'Bojownik wspaniały (syjamski)'],
            ['species_id'=>8,'name'=>'Danio pręgowany'],
            ['species_id'=>8,'name'=>'Kirysek pstry'],
            ['species_id'=>8,'name'=>'Motylek Ramireza'],
            ['species_id'=>8,'name'=>'Skalar'],
            ['species_id'=>8,'name'=>'Symphysodon '],
            ['species_id'=>8,'name'=>'Zmienniak plamisty'],
            ['species_id'=>8,'name'=>'bystrzyk neonowy'],
            ['species_id'=>8,'name'=>'gupik'],
        );

        foreach ($breeds as $breed){
            DB::table('animal_breeds')->insert([
                'species_id' => $breed['species_id'],
                'name' => strtolower($breed['name']),
                'created_at' => $faker->dateTime,
                'created_user_id' => 1,
                'edited_at' => null,
                'edited_user_id' => null,
                'deleted_at' => null,
                'deleted_user_id' => null,
            ]);
        }
    }
}
